[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
hakata_perpetuals = "CkawHJw5TVjUt1ggAZtuo3hgHBMptJHtxXk6A6nY5RWg"

[programs.localnet]
hakata_perpetuals = "CkawHJw5TVjUt1ggAZtuo3hgHBMptJHtxXk6A6nY5RWg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/hakata-perpetuals/tests/anchor/*.ts"
